// @generated drizzle-zero signature:sha256:565a66587bcb0c2b47f5b6c129bef502a82985254945c7a0956f03edf7596d6a
// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";
import type { ZeroCustomType } from "drizzle-zero";
import type { default as zeroSchema } from "../../config/drizzle-zero.config";

const akahuAccountTable = {
  name: "akahuAccount",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    akahuId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "akahu_id",
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    type: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    formattedAccount: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "formatted_account",
    },
    balance: {
      type: "json",
      optional: true,
      customType: null as unknown as {
        current: number;
        available?: number;
        limit?: number;
      },
    },
    syncedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "synced_at",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "akahu_account",
} as const;
const akahuTransactionTable = {
  name: "akahuTransaction",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    accountId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "account_id",
    },
    akahuId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "akahu_id",
    },
    date: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    description: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    amount: {
      type: "json",
      optional: false,
      customType: null as unknown as { value: number; currency: string },
    },
    balance: {
      type: "json",
      optional: true,
      customType: null as unknown as { current: number; currency: string },
    },
    type: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    category: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    merchant: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    categoryId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "category_id",
    },
    meta: {
      type: "json",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "akahuTransaction",
        "meta"
      >,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "akahu_transaction",
} as const;
const budgetTable = {
  name: "budget",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    period: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    periodStart: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "period_start",
    },
    periodEnd: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "period_end",
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const budgetIncomeTable = {
  name: "budgetIncome",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    budgetId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "budget_id",
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    amount: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    frequency: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    notes: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    referenceDatePayday: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "reference_date_payday",
    },
    adjustForWeekends: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "adjust_for_weekends",
    },
    nextPaydayDate: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "next_payday_date",
    },
    expectedFromAccount: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "expected_from_account",
    },
    autoTagEnabled: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "auto_tag_enabled",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "budget_income",
} as const;
const budgetIncomeTransactionTable = {
  name: "budgetIncomeTransaction",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    incomeId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "income_id",
    },
    transactionId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "transaction_id",
    },
    fromAccount: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "from_account",
    },
    linkedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "linked_at",
    },
    autoTagged: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "auto_tagged",
    },
  },
  primaryKey: ["id"],
  serverName: "budget_income_transaction",
} as const;
const categoryAllocationTable = {
  name: "categoryAllocation",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    budgetId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "budget_id",
    },
    categoryId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "category_id",
    },
    allocatedAmount: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "allocated_amount",
    },
    notes: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "category_allocation",
} as const;
const fixedExpenseTable = {
  name: "fixedExpense",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    budgetId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "budget_id",
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    categoryId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "category_id",
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    description: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    amount: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    frequency: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    matchPattern: {
      type: "json",
      optional: true,
      customType: null as unknown as {
        merchant?: string;
        description?: string;
      },
      serverName: "match_pattern",
    },
    nextDueDate: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "next_due_date",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "fixed_expense",
} as const;
const fixedExpenseTransactionTable = {
  name: "fixedExpenseTransaction",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    fixedExpenseId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "fixed_expense_id",
    },
    transactionId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "transaction_id",
    },
    linkedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "linked_at",
    },
    autoTagged: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "auto_tagged",
    },
  },
  primaryKey: ["id"],
  serverName: "fixed_expense_transaction",
} as const;
const transactionCategoryTable = {
  name: "transactionCategory",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    color: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    description: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "transaction_category",
} as const;
const transactionReferenceTable = {
  name: "transactionReference",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    merchant: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    description: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    fromAccount: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "from_account",
    },
    categoryId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "category_id",
    },
    amountCondition: {
      type: "json",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "transactionReference",
        "amountCondition"
      >,
      serverName: "amount_condition",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "transaction_reference",
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    akahuAccount: akahuAccountTable,
    akahuTransaction: akahuTransactionTable,
    budget: budgetTable,
    budgetIncome: budgetIncomeTable,
    budgetIncomeTransaction: budgetIncomeTransactionTable,
    categoryAllocation: categoryAllocationTable,
    fixedExpense: fixedExpenseTable,
    fixedExpenseTransaction: fixedExpenseTransactionTable,
    transactionCategory: transactionCategoryTable,
    transactionReference: transactionReferenceTable,
  },
  relationships: {},
  enableLegacyQueries: false,
  enableLegacyMutators: false,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "akahuAccount" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type AkahuAccount = Row<(typeof schema)["tables"]["akahuAccount"]>;
/**
 * Represents a row from the "akahuTransaction" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type AkahuTransaction = Row<
  (typeof schema)["tables"]["akahuTransaction"]
>;
/**
 * Represents a row from the "budget" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Budget = Row<(typeof schema)["tables"]["budget"]>;
/**
 * Represents a row from the "budgetIncome" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type BudgetIncome = Row<(typeof schema)["tables"]["budgetIncome"]>;
/**
 * Represents a row from the "budgetIncomeTransaction" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type BudgetIncomeTransaction = Row<
  (typeof schema)["tables"]["budgetIncomeTransaction"]
>;
/**
 * Represents a row from the "categoryAllocation" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type CategoryAllocation = Row<
  (typeof schema)["tables"]["categoryAllocation"]
>;
/**
 * Represents a row from the "fixedExpense" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type FixedExpense = Row<(typeof schema)["tables"]["fixedExpense"]>;
/**
 * Represents a row from the "fixedExpenseTransaction" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type FixedExpenseTransaction = Row<
  (typeof schema)["tables"]["fixedExpenseTransaction"]
>;
/**
 * Represents a row from the "transactionCategory" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type TransactionCategory = Row<
  (typeof schema)["tables"]["transactionCategory"]
>;
/**
 * Represents a row from the "transactionReference" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type TransactionReference = Row<
  (typeof schema)["tables"]["transactionReference"]
>;

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module "@rocicorp/zero" {
  interface DefaultTypes {
    schema: Schema;
  }
}
