// @generated drizzle-zero signature:sha256:841027075a34e057077d1a53a08aa93e1461d3b13948173a3c6c59a519bd5501
// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";

const akahuAccountTable = {
  name: "akahuAccount",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    akahuId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "akahu_id",
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    type: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    formattedAccount: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "formatted_account",
    },
    balance: {
      type: "json",
      optional: true,
      customType: null as unknown as {
        current: number;
        available?: number;
        limit?: number;
      },
    },
    syncedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "synced_at",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "akahu_account",
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    akahuAccount: akahuAccountTable,
  },
  relationships: {},
  enableLegacyQueries: false,
  enableLegacyMutators: false,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "akahuAccount" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type AkahuAccount = Row<(typeof schema)["tables"]["akahuAccount"]>;

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module "@rocicorp/zero" {
  interface DefaultTypes {
    schema: Schema;
  }
}
