import { drizzleZeroConfig } from "drizzle-zero";
import * as drizzleSchema from "../db/schema";

export default drizzleZeroConfig(drizzleSchema, {
  tables: {
    akahuAccount: {
      id: true,
      userId: true,
      akahuId: true,
      name: true,
      type: true,
      formattedAccount: true,
      balance: true,
      syncedAt: true,
      createdAt: true,
      updatedAt: true,
    },
    transactionCategory: {
      id: true,
      userId: true,
      name: true,
      color: true,
      description: true,
      createdAt: true,
      updatedAt: true,
    },
    transactionReference: {
      id: true,
      userId: true,
      merchant: true,
      description: true,
      fromAccount: true,
      categoryId: true,
      amountCondition: true,
      createdAt: true,
      updatedAt: true,
    },
    akahuTransaction: {
      id: true,
      userId: true,
      accountId: true,
      akahuId: true,
      date: true,
      description: true,
      amount: true,
      balance: true,
      type: true,
      category: true,
      merchant: true,
      categoryId: true,
      meta: true,
      createdAt: true,
      updatedAt: true,
    },
    budget: {
      id: true,
      userId: true,
      name: true,
      period: true,
      periodStart: true,
      periodEnd: true,
      status: true,
      createdAt: true,
      updatedAt: true,
    },
    budgetIncome: {
      id: true,
      budgetId: true,
      userId: true,
      name: true,
      amount: true,
      frequency: true,
      notes: true,
      referenceDatePayday: true,
      adjustForWeekends: true,
      nextPaydayDate: true,
      expectedFromAccount: true,
      autoTagEnabled: true,
      createdAt: true,
      updatedAt: true,
    },
    budgetIncomeTransaction: {
      id: true,
      incomeId: true,
      transactionId: true,
      fromAccount: true,
      linkedAt: true,
      autoTagged: true,
    },
    fixedExpense: {
      id: true,
      budgetId: true,
      userId: true,
      categoryId: true,
      name: true,
      description: true,
      amount: true,
      frequency: true,
      matchPattern: true,
      nextDueDate: true,
      createdAt: true,
      updatedAt: true,
    },
    fixedExpenseTransaction: {
      id: true,
      fixedExpenseId: true,
      transactionId: true,
      linkedAt: true,
      autoTagged: true,
    },
    categoryAllocation: {
      id: true,
      budgetId: true,
      categoryId: true,
      allocatedAmount: true,
      notes: true,
      createdAt: true,
      updatedAt: true,
    },
  },
});
